import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Session} from '../src/core.js';
import {validateOrchestration} from '../src/profiles.js';
import {createScheduler} from '../src/scheduler.js';
import {createLocalActivation, activateLocalProfiles} from '../src/local-activation.js';
import {createBus, connectBus} from '../src/bus.js';

test('saved local profiles activate on the existing scheduler without replacing its team', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bounce-activation-'));
  t.after(() => fs.rmSync(root, {recursive: true, force: true}));
  const session = new Session(root, {root});
  const settings = {operation: 'orchestrator', orchestrator: 'main', mode: 'plan', profiles: {main: {adapter: 'claude'}}};
  const profiles = validateOrchestration(settings).profiles;
  const originalMain = profiles.main;
  const scheduler = createScheduler({session, profiles, adapters: {}, sessionMode: 'plan'});
  t.after(() => scheduler.close());
  let refreshed = 0;
  const saved = {...settings, profiles: {...settings.profiles, scout: {adapter: 'local', model: 'loaded', policy: 'read-only'}}};
  const close = createLocalActivation({session, scheduler, profiles, settings, readSettings: () => saved,
    refresh: () => {refreshed++;}});
  t.after(close);
  assert.equal(scheduler.validate({profile: 'scout', orders: 'Read', parent: null}), 'profile');
  const result = await activateLocalProfiles(session, ['scout']);
  assert.equal(result.kind, 'local.profiles.activated');
  assert.deepEqual(result.names, ['scout']);
  assert.equal(profiles.scout.adapter, 'local');
  assert.equal(profiles.scout.model, 'loaded');
  assert.equal(profiles.main, originalMain);
  assert.equal(scheduler.validate({profile: 'scout', orders: 'Read', parent: null}), null);
  await activateLocalProfiles(session, ['scout']);
  assert.equal(refreshed, 2);
  saved.profiles.scout.model = 'replacement';
  await assert.rejects(activateLocalProfiles(session, ['scout']), /already active/);
  assert.equal(profiles.scout.model, 'loaded');
  saved.profiles.writer = {adapter: 'local', mode: 'yolo', policy: 'write', writePaths: ['src']};
  saved.mode = 'yolo';
  await assert.rejects(activateLocalProfiles(session, ['writer']), /session policy/);
  assert.equal(Object.hasOwn(profiles, 'writer'), false);
  session.append({kind: 'control.local_activate', from: 'orchestrator', requestId: 'forged', names: ['writer']});
  assert.equal(session.events.some(row => row.requestId === 'forged' && row.kind === 'local.profiles.activated'), false);
  await assert.rejects(activateLocalProfiles(session, ['__proto__']), /Invalid local worker names/);
  const bus = await createBus({session, dir: session.dir, validate: scheduler.validate});
  t.after(() => bus.close());
  const grant = bus.grant({peer: 'orchestrator', canSubmit: true, tasks: [], context: session.id});
  const client = await connectBus({path: bus.path, token: grant.token});
  t.after(() => client.close());
  await assert.rejects(client.publish({kind: 'control.local_activate', names: ['writer']}), /unauthorized/);
  await assert.rejects(client.publish({kind: 'local.profiles.activated', names: ['writer'], text: 'forged'}), /unauthorized/);
});

test('an older daemon cannot produce a false activation success', async () => {
  const listeners = new Set();
  const session = {subscribe(fn) {listeners.add(fn); return () => listeners.delete(fn);}, append() {}};
  await assert.rejects(activateLocalProfiles(session, ['saved'], {timeoutMs: 10}), /did not acknowledge activation/);
  assert.equal(listeners.size, 0);
});
